### ISSUE TITLE
are you going to open both training/inference codes?

### ISSUE THREAD

**Issue by AwayFromKeyboardwarrior** [likyoo/DiffMatch#1]
are you going to open both training/inference codes?

Thanks a lot for your contribution =D

I liked your paper so much!

**Comment by likyoo** [comment]
Sincerely thank you for your interest !
We plan to release all the codes in June this year. 😄

**Comment by likyoo** [comment]
Our code is available now! @AwayFromKeyboardwarrior

**Comment by AwayFromKeyboardwarrior** [comment]
Thank you!
